import { Router } from "express";
import smtp from "./smtp/router.js";
import general from "./general/router.js";
import notifications from "./notifications/router.js";
import security from "./security/router.js";
import apiKeys from "./security/api-keys/router.js";
import authMethods from "./auth-methods/router.js";
import sso from "./sso/router.js";
import branding from "./branding/router.js";
import emailTemplates from "./email-templates/router.js";
const r = Router();
r.use("/smtp", smtp);
r.use("/general", general);
r.use("/notifications", notifications);
r.use("/security", security);
r.use("/security/api-keys", apiKeys);
r.use("/auth-methods", authMethods);
r.use("/sso", sso);
r.use("/branding", branding);
r.use("/email-templates", emailTemplates);
export default r;
