-- AUTO-GENERATED: do not edit by hand
-- Source: src/constants/permissions.js

CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS public.permissions (
  id          uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  code        text UNIQUE NOT NULL,
  name        text NOT NULL,
  description text,
  created_at  timestamptz NOT NULL DEFAULT now(),
  updated_at  timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.permissions
  ALTER COLUMN id SET DEFAULT gen_random_uuid();

INSERT INTO public.permissions (code, name, description)
VALUES
  ('system.manage', 'System Manage', NULL),
  ('users.manage', 'Users Manage', NULL),
  ('roles.manage', 'Roles Manage', NULL),
  ('settings.manage', 'Settings Manage', NULL),
  ('workflows.manage', 'Workflows Manage', NULL),
  ('inbox.manage', 'Inbox Manage', NULL),
  ('files.read', 'Files Read', NULL),
  ('audit.read', 'Audit Read', NULL),
  ('tickets.manage', 'Tickets Manage', NULL),
  ('knowledge.manage', 'Knowledge Manage', NULL),
  ('analytics.view', 'Analytics View', NULL),
  ('apiKeys.manage', 'ApiKeys Manage', NULL),
  ('tickets.list', 'Tickets List', NULL),
  ('tickets.read', 'Tickets Read', NULL),
  ('tickets.create', 'Tickets Create', NULL),
  ('tickets.update', 'Tickets Update', NULL),
  ('tickets.delete', 'Tickets Delete', NULL),
  ('tickets.assign', 'Tickets Assign', NULL),
  ('tickets.release', 'Tickets Release', NULL),
  ('tickets.claim', 'Tickets Claim', NULL),
  ('tickets.unclaim', 'Tickets Unclaim', NULL),
  ('tickets.status.set', 'Tickets Status Set', NULL),
  ('tickets.priority.set', 'Tickets Priority Set', NULL),
  ('tickets.severity.set', 'Tickets Severity Set', NULL),
  ('tickets.notes.read', 'Tickets Notes Read', NULL),
  ('tickets.notes.add', 'Tickets Notes Add', NULL),
  ('tickets.watchers.read', 'Tickets Watchers Read', NULL),
  ('tickets.watchers.add', 'Tickets Watchers Add', NULL),
  ('tickets.watchers.remove', 'Tickets Watchers Remove', NULL),
  ('tickets.attachments.read', 'Tickets Attachments Read', NULL),
  ('tickets.attachments.add', 'Tickets Attachments Add', NULL),
  ('tickets.events.read', 'Tickets Events Read', NULL),
  ('tickets.close', 'Tickets Close', NULL),
  ('tickets.reopen', 'Tickets Reopen', NULL),
  ('knowledge.faqs.list', 'Knowledge Faqs List', NULL),
  ('knowledge.faqs.read', 'Knowledge Faqs Read', NULL),
  ('knowledge.faqs.create', 'Knowledge Faqs Create', NULL),
  ('knowledge.faqs.update', 'Knowledge Faqs Update', NULL),
  ('knowledge.faqs.delete', 'Knowledge Faqs Delete', NULL),
  ('knowledge.faqs.origins.list', 'Knowledge Faqs Origins List', NULL),
  ('knowledge.faqs.origins.create', 'Knowledge Faqs Origins Create', NULL),
  ('knowledge.faqs.origins.delete', 'Knowledge Faqs Origins Delete', NULL),
  ('knowledge.kb.articles.list', 'Knowledge Kb Articles List', NULL),
  ('knowledge.kb.articles.read', 'Knowledge Kb Articles Read', NULL),
  ('knowledge.kb.articles.create', 'Knowledge Kb Articles Create', NULL),
  ('knowledge.kb.articles.update', 'Knowledge Kb Articles Update', NULL),
  ('knowledge.kb.articles.delete', 'Knowledge Kb Articles Delete', NULL),
  ('knowledge.kb.tags.list', 'Knowledge Kb Tags List', NULL),
  ('knowledge.kb.tags.create', 'Knowledge Kb Tags Create', NULL),
  ('knowledge.kb.tags.delete', 'Knowledge Kb Tags Delete', NULL),
  ('knowledge.kb.tagMap.list', 'Knowledge Kb TagMap List', NULL),
  ('knowledge.kb.tagMap.create', 'Knowledge Kb TagMap Create', NULL),
  ('knowledge.kb.tagMap.delete', 'Knowledge Kb TagMap Delete', NULL),
  ('knowledge.kb.ratings.list', 'Knowledge Kb Ratings List', NULL),
  ('knowledge.kb.ratings.delete', 'Knowledge Kb Ratings Delete', NULL),
  ('knowledge.videos.list', 'Knowledge Videos List', NULL),
  ('knowledge.videos.read', 'Knowledge Videos Read', NULL),
  ('knowledge.videos.create', 'Knowledge Videos Create', NULL),
  ('knowledge.videos.update', 'Knowledge Videos Update', NULL),
  ('knowledge.videos.delete', 'Knowledge Videos Delete', NULL),
  ('knowledge.videoCategories.list', 'Knowledge VideoCategories List', NULL),
  ('knowledge.videoCategories.create', 'Knowledge VideoCategories Create', NULL),
  ('knowledge.videoCategories.update', 'Knowledge VideoCategories Update', NULL),
  ('knowledge.videoCategories.delete', 'Knowledge VideoCategories Delete', NULL),
  ('knowledge.search.run', 'Knowledge Search Run', NULL),
  ('analytics.dashboards.view', 'Analytics Dashboards View', NULL),
  ('analytics.reports.run', 'Analytics Reports Run', NULL),
  ('analytics.reports.export', 'Analytics Reports Export', NULL),
  ('analytics.exports.download', 'Analytics Exports Download', NULL),
  ('system.users.list', 'System Users List', NULL),
  ('system.users.read', 'System Users Read', NULL),
  ('system.users.create', 'System Users Create', NULL),
  ('system.users.update', 'System Users Update', NULL),
  ('system.users.delete', 'System Users Delete', NULL),
  ('system.users.roles.assign', 'System Users Roles Assign', NULL),
  ('system.users.roles.remove', 'System Users Roles Remove', NULL),
  ('system.users.tiers.read', 'System Users Tiers Read', NULL),
  ('system.users.tiers.add', 'System Users Tiers Add', NULL),
  ('system.users.tiers.remove', 'System Users Tiers Remove', NULL),
  ('system.users.supportGroups.read', 'System Users SupportGroups Read', NULL),
  ('system.users.supportGroups.add', 'System Users SupportGroups Add', NULL),
  ('system.users.supportGroups.remove', 'System Users SupportGroups Remove', NULL),
  ('system.roles.list', 'System Roles List', NULL),
  ('system.roles.read', 'System Roles Read', NULL),
  ('system.roles.create', 'System Roles Create', NULL),
  ('system.roles.update', 'System Roles Update', NULL),
  ('system.roles.delete', 'System Roles Delete', NULL),
  ('system.roles.permissions.list', 'System Roles Permissions List', NULL),
  ('system.roles.permissions.add', 'System Roles Permissions Add', NULL),
  ('system.roles.permissions.remove', 'System Roles Permissions Remove', NULL),
  ('system.lookups.statuses.list', 'System Lookups Statuses List', NULL),
  ('system.lookups.statuses.create', 'System Lookups Statuses Create', NULL),
  ('system.lookups.statuses.update', 'System Lookups Statuses Update', NULL),
  ('system.lookups.statuses.delete', 'System Lookups Statuses Delete', NULL),
  ('system.lookups.priorities.list', 'System Lookups Priorities List', NULL),
  ('system.lookups.priorities.create', 'System Lookups Priorities Create', NULL),
  ('system.lookups.priorities.update', 'System Lookups Priorities Update', NULL),
  ('system.lookups.priorities.delete', 'System Lookups Priorities Delete', NULL),
  ('system.lookups.severities.list', 'System Lookups Severities List', NULL),
  ('system.lookups.severities.create', 'System Lookups Severities Create', NULL),
  ('system.lookups.severities.update', 'System Lookups Severities Update', NULL),
  ('system.lookups.severities.delete', 'System Lookups Severities Delete', NULL),
  ('system.lookups.sources.list', 'System Lookups Sources List', NULL),
  ('system.lookups.sources.create', 'System Lookups Sources Create', NULL),
  ('system.lookups.sources.update', 'System Lookups Sources Update', NULL),
  ('system.lookups.sources.delete', 'System Lookups Sources Delete', NULL),
  ('system.lookups.systemCategory.list', 'System Lookups SystemCategory List', NULL),
  ('system.lookups.systemCategory.create', 'System Lookups SystemCategory Create', NULL),
  ('system.lookups.systemCategory.update', 'System Lookups SystemCategory Update', NULL),
  ('system.lookups.systemCategory.delete', 'System Lookups SystemCategory Delete', NULL),
  ('system.lookups.systems.list', 'System Lookups Systems List', NULL),
  ('system.lookups.systems.read', 'System Lookups Systems Read', NULL),
  ('system.lookups.systems.create', 'System Lookups Systems Create', NULL),
  ('system.lookups.systems.update', 'System Lookups Systems Update', NULL),
  ('system.lookups.systems.delete', 'System Lookups Systems Delete', NULL),
  ('system.lookups.systemModules.list', 'System Lookups SystemModules List', NULL),
  ('system.lookups.systemModules.read', 'System Lookups SystemModules Read', NULL),
  ('system.lookups.systemModules.create', 'System Lookups SystemModules Create', NULL),
  ('system.lookups.systemModules.update', 'System Lookups SystemModules Update', NULL),
  ('system.lookups.systemModules.delete', 'System Lookups SystemModules Delete', NULL),
  ('system.lookups.issueCategories.list', 'System Lookups IssueCategories List', NULL),
  ('system.lookups.issueCategories.read', 'System Lookups IssueCategories Read', NULL),
  ('system.lookups.issueCategories.create', 'System Lookups IssueCategories Create', NULL),
  ('system.lookups.issueCategories.update', 'System Lookups IssueCategories Update', NULL),
  ('system.lookups.issueCategories.delete', 'System Lookups IssueCategories Delete', NULL),
  ('system.lookups.supportTiers.list', 'System Lookups SupportTiers List', NULL),
  ('system.lookups.supportTiers.create', 'System Lookups SupportTiers Create', NULL),
  ('system.lookups.supportTiers.update', 'System Lookups SupportTiers Update', NULL),
  ('system.lookups.supportTiers.delete', 'System Lookups SupportTiers Delete', NULL),
  ('system.lookups.supportGroups.list', 'System Lookups SupportGroups List', NULL),
  ('system.lookups.supportGroups.create', 'System Lookups SupportGroups Create', NULL),
  ('system.lookups.supportGroups.update', 'System Lookups SupportGroups Update', NULL),
  ('system.lookups.supportGroups.delete', 'System Lookups SupportGroups Delete', NULL),
  ('system.settings.general.read', 'System Settings General Read', NULL),
  ('system.settings.general.update', 'System Settings General Update', NULL),
  ('system.settings.smtp.read', 'System Settings Smtp Read', NULL),
  ('system.settings.smtp.update', 'System Settings Smtp Update', NULL),
  ('system.settings.security.read', 'System Settings Security Read', NULL),
  ('system.settings.security.update', 'System Settings Security Update', NULL),
  ('system.settings.branding.read', 'System Settings Branding Read', NULL),
  ('system.settings.branding.update', 'System Settings Branding Update', NULL),
  ('system.settings.emailTemplates.read', 'System Settings EmailTemplates Read', NULL),
  ('system.settings.emailTemplates.update', 'System Settings EmailTemplates Update', NULL),
  ('system.files.list', 'System Files List', NULL),
  ('system.files.read', 'System Files Read', NULL),
  ('system.files.delete', 'System Files Delete', NULL),
  ('system.audit.read', 'System Audit Read', NULL),
  ('system.workflows.rules.list', 'System Workflows Rules List', NULL),
  ('system.workflows.rules.create', 'System Workflows Rules Create', NULL),
  ('system.workflows.rules.update', 'System Workflows Rules Update', NULL),
  ('system.workflows.rules.delete', 'System Workflows Rules Delete', NULL),
  ('system.workflows.runs.list', 'System Workflows Runs List', NULL),
  ('system.workflows.runs.read', 'System Workflows Runs Read', NULL),
  ('system.inbox.emails.list', 'System Inbox Emails List', NULL),
  ('system.inbox.emails.read', 'System Inbox Emails Read', NULL),
  ('system.inbox.emails.create', 'System Inbox Emails Create', NULL),
  ('system.inbox.emails.update', 'System Inbox Emails Update', NULL),
  ('system.inbox.emails.delete', 'System Inbox Emails Delete', NULL),
  ('system.security.apiKeys.list', 'System Security ApiKeys List', NULL),
  ('system.security.apiKeys.read', 'System Security ApiKeys Read', NULL),
  ('system.security.apiKeys.create', 'System Security ApiKeys Create', NULL),
  ('system.security.apiKeys.revoke', 'System Security ApiKeys Revoke', NULL),
  ('admin.me.read', 'Admin Me Read', NULL),
  ('admin.me.update', 'Admin Me Update', NULL),
  ('admin.preferences.read', 'Admin Preferences Read', NULL),
  ('admin.preferences.update', 'Admin Preferences Update', NULL),
  ('admin.notifications.read', 'Admin Notifications Read', NULL)
ON CONFLICT (code) DO UPDATE
  SET name = EXCLUDED.name,
      description = COALESCE(EXCLUDED.description, public.permissions.description),
      updated_at = now();
