// Centralized permission names for RBAC
// Keep in sync with scripts/migrations/*permissions*_seed.sql files

export const PERMISSIONS = Object.freeze({
  // Coarse-grained (back-compat)
  SYSTEM_MANAGE: "system.manage",
  USERS_MANAGE: "users.manage",
  ROLES_MANAGE: "roles.manage",
  SETTINGS_MANAGE: "settings.manage",
  WORKFLOWS_MANAGE: "workflows.manage",
  INBOX_MANAGE: "inbox.manage",
  FILES_READ: "files.read",
  AUDIT_READ: "audit.read",
  TICKETS_MANAGE: "tickets.manage",
  KNOWLEDGE_MANAGE: "knowledge.manage",
  ANALYTICS_VIEW: "analytics.view",
  API_KEYS_MANAGE: "apiKeys.manage",

  // Tickets (granular)
  TICKETS_LIST: "tickets.list",
  TICKETS_READ: "tickets.read",
  TICKETS_CREATE: "tickets.create",
  TICKETS_UPDATE: "tickets.update",
  TICKETS_DELETE: "tickets.delete",
  TICKETS_ASSIGN: "tickets.assign",
  TICKETS_RELEASE: "tickets.release",
  TICKETS_CLAIM: "tickets.claim",
  TICKETS_UNCLAIM: "tickets.unclaim",
  TICKETS_STATUS_SET: "tickets.status.set",
  TICKETS_PRIORITY_SET: "tickets.priority.set",
  TICKETS_SEVERITY_SET: "tickets.severity.set",
  TICKETS_NOTES_READ: "tickets.notes.read",
  TICKETS_NOTES_ADD: "tickets.notes.add",
  TICKETS_WATCHERS_READ: "tickets.watchers.read",
  TICKETS_WATCHERS_ADD: "tickets.watchers.add",
  TICKETS_WATCHERS_REMOVE: "tickets.watchers.remove",
  TICKETS_ATTACHMENTS_READ: "tickets.attachments.read",
  TICKETS_ATTACHMENTS_ADD: "tickets.attachments.add",
  TICKETS_EVENTS_READ: "tickets.events.read",
  TICKETS_CLOSE: "tickets.close",
  TICKETS_REOPEN: "tickets.reopen",

  // Knowledge: FAQs
  KNOW_FAQS_LIST: "knowledge.faqs.list",
  KNOW_FAQS_READ: "knowledge.faqs.read",
  KNOW_FAQS_CREATE: "knowledge.faqs.create",
  KNOW_FAQS_UPDATE: "knowledge.faqs.update",
  KNOW_FAQS_DELETE: "knowledge.faqs.delete",
  // Knowledge: FAQ origins
  KNOW_FAQ_ORIGINS_LIST: "knowledge.faqs.origins.list",
  KNOW_FAQ_ORIGINS_CREATE: "knowledge.faqs.origins.create",
  KNOW_FAQ_ORIGINS_DELETE: "knowledge.faqs.origins.delete",
  // Knowledge: KB Articles
  KNOW_KB_ARTICLES_LIST: "knowledge.kb.articles.list",
  KNOW_KB_ARTICLES_READ: "knowledge.kb.articles.read",
  KNOW_KB_ARTICLES_CREATE: "knowledge.kb.articles.create",
  KNOW_KB_ARTICLES_UPDATE: "knowledge.kb.articles.update",
  KNOW_KB_ARTICLES_DELETE: "knowledge.kb.articles.delete",
  // Knowledge: KB Tags
  KNOW_KB_TAGS_LIST: "knowledge.kb.tags.list",
  KNOW_KB_TAGS_CREATE: "knowledge.kb.tags.create",
  KNOW_KB_TAGS_DELETE: "knowledge.kb.tags.delete",
  // Knowledge: KB Tag Map
  KNOW_KB_TAGMAP_LIST: "knowledge.kb.tagMap.list",
  KNOW_KB_TAGMAP_CREATE: "knowledge.kb.tagMap.create",
  KNOW_KB_TAGMAP_DELETE: "knowledge.kb.tagMap.delete",
  // Knowledge: KB Ratings
  KNOW_KB_RATINGS_LIST: "knowledge.kb.ratings.list",
  KNOW_KB_RATINGS_DELETE: "knowledge.kb.ratings.delete",
  // Knowledge: Videos & Categories
  KNOW_VIDEOS_LIST: "knowledge.videos.list",
  KNOW_VIDEOS_READ: "knowledge.videos.read",
  KNOW_VIDEOS_CREATE: "knowledge.videos.create",
  KNOW_VIDEOS_UPDATE: "knowledge.videos.update",
  KNOW_VIDEOS_DELETE: "knowledge.videos.delete",
  KNOW_VIDEO_CATEGORIES_LIST: "knowledge.videoCategories.list",
  KNOW_VIDEO_CATEGORIES_CREATE: "knowledge.videoCategories.create",
  KNOW_VIDEO_CATEGORIES_UPDATE: "knowledge.videoCategories.update",
  KNOW_VIDEO_CATEGORIES_DELETE: "knowledge.videoCategories.delete",
  // Knowledge: Search
  KNOW_SEARCH_RUN: "knowledge.search.run",

  // Analytics
  ANALYTICS_DASHBOARDS_VIEW: "analytics.dashboards.view",
  ANALYTICS_REPORTS_RUN: "analytics.reports.run",
  ANALYTICS_REPORTS_EXPORT: "analytics.reports.export",
  ANALYTICS_EXPORTS_DOWNLOAD: "analytics.exports.download",

  // System: Users
  SYS_USERS_LIST: "system.users.list",
  SYS_USERS_READ: "system.users.read",
  SYS_USERS_CREATE: "system.users.create",
  SYS_USERS_UPDATE: "system.users.update",
  SYS_USERS_DELETE: "system.users.delete",
  SYS_USERS_ROLES_ASSIGN: "system.users.roles.assign",
  SYS_USERS_ROLES_REMOVE: "system.users.roles.remove",

  // System: Roles
  SYS_ROLES_LIST: "system.roles.list",
  SYS_ROLES_READ: "system.roles.read",
  SYS_ROLES_CREATE: "system.roles.create",
  SYS_ROLES_UPDATE: "system.roles.update",
  SYS_ROLES_DELETE: "system.roles.delete",
  SYS_ROLES_PERMS_LIST: "system.roles.permissions.list",
  SYS_ROLES_PERMS_ADD: "system.roles.permissions.add",
  SYS_ROLES_PERMS_REMOVE: "system.roles.permissions.remove",

  // System: Lookups (catalogs)
  SYS_LOOKUPS_STATUSES_LIST: "system.lookups.statuses.list",
  SYS_LOOKUPS_STATUSES_CREATE: "system.lookups.statuses.create",
  SYS_LOOKUPS_STATUSES_UPDATE: "system.lookups.statuses.update",
  SYS_LOOKUPS_STATUSES_DELETE: "system.lookups.statuses.delete",

  SYS_LOOKUPS_PRIORITIES_LIST: "system.lookups.priorities.list",
  SYS_LOOKUPS_PRIORITIES_CREATE: "system.lookups.priorities.create",
  SYS_LOOKUPS_PRIORITIES_UPDATE: "system.lookups.priorities.update",
  SYS_LOOKUPS_PRIORITIES_DELETE: "system.lookups.priorities.delete",

  SYS_LOOKUPS_SEVERITIES_LIST: "system.lookups.severities.list",
  SYS_LOOKUPS_SEVERITIES_CREATE: "system.lookups.severities.create",
  SYS_LOOKUPS_SEVERITIES_UPDATE: "system.lookups.severities.update",
  SYS_LOOKUPS_SEVERITIES_DELETE: "system.lookups.severities.delete",

  SYS_LOOKUPS_SOURCES_LIST: "system.lookups.sources.list",
  SYS_LOOKUPS_SOURCES_CREATE: "system.lookups.sources.create",
  SYS_LOOKUPS_SOURCES_UPDATE: "system.lookups.sources.update",
  SYS_LOOKUPS_SOURCES_DELETE: "system.lookups.sources.delete",

  SYS_LOOKUPS_SYSTEM_CATEGORY_LIST: "system.lookups.systemCategory.list",
  SYS_LOOKUPS_SYSTEM_CATEGORY_CREATE: "system.lookups.systemCategory.create",
  SYS_LOOKUPS_SYSTEM_CATEGORY_UPDATE: "system.lookups.systemCategory.update",
  SYS_LOOKUPS_SYSTEM_CATEGORY_DELETE: "system.lookups.systemCategory.delete",

  SYS_LOOKUPS_SYSTEMS_LIST: "system.lookups.systems.list",
  SYS_LOOKUPS_SYSTEMS_READ: "system.lookups.systems.read",
  SYS_LOOKUPS_SYSTEMS_CREATE: "system.lookups.systems.create",
  SYS_LOOKUPS_SYSTEMS_UPDATE: "system.lookups.systems.update",
  SYS_LOOKUPS_SYSTEMS_DELETE: "system.lookups.systems.delete",

  SYS_LOOKUPS_SYSTEM_MODULES_LIST: "system.lookups.systemModules.list",
  SYS_LOOKUPS_SYSTEM_MODULES_READ: "system.lookups.systemModules.read",
  SYS_LOOKUPS_SYSTEM_MODULES_CREATE: "system.lookups.systemModules.create",
  SYS_LOOKUPS_SYSTEM_MODULES_UPDATE: "system.lookups.systemModules.update",
  SYS_LOOKUPS_SYSTEM_MODULES_DELETE: "system.lookups.systemModules.delete",

  SYS_LOOKUPS_ISSUE_CATEGORIES_LIST: "system.lookups.issueCategories.list",
  SYS_LOOKUPS_ISSUE_CATEGORIES_READ: "system.lookups.issueCategories.read",
  SYS_LOOKUPS_ISSUE_CATEGORIES_CREATE: "system.lookups.issueCategories.create",
  SYS_LOOKUPS_ISSUE_CATEGORIES_UPDATE: "system.lookups.issueCategories.update",
  SYS_LOOKUPS_ISSUE_CATEGORIES_DELETE: "system.lookups.issueCategories.delete",

  // System: Agents
  SYS_AGENTS_GROUPS_LIST: "system.agents.groups.list",
  SYS_AGENTS_GROUPS_READ: "system.agents.groups.read",
  SYS_AGENTS_GROUPS_CREATE: "system.agents.groups.create",
  SYS_AGENTS_GROUPS_UPDATE: "system.agents.groups.update",
  SYS_AGENTS_GROUPS_DELETE: "system.agents.groups.delete",
  SYS_AGENTS_GROUP_MEMBERS_LIST: "system.agents.groupMembers.list",
  SYS_AGENTS_GROUP_MEMBERS_ADD: "system.agents.groupMembers.add",
  SYS_AGENTS_GROUP_MEMBERS_REMOVE: "system.agents.groupMembers.remove",
  SYS_AGENTS_TIERS_LIST: "system.agents.tiers.list",
  SYS_AGENTS_TIERS_READ: "system.agents.tiers.read",
  SYS_AGENTS_TIERS_CREATE: "system.agents.tiers.create",
  SYS_AGENTS_TIERS_UPDATE: "system.agents.tiers.update",
  SYS_AGENTS_TIERS_DELETE: "system.agents.tiers.delete",
  SYS_AGENTS_TIER_MEMBERS_LIST: "system.agents.tierMembers.list",
  SYS_AGENTS_TIER_MEMBERS_ADD: "system.agents.tierMembers.add",
  SYS_AGENTS_TIER_MEMBERS_REMOVE: "system.agents.tierMembers.remove",

  // System: Settings
  SYS_SETTINGS_GENERAL_READ: "system.settings.general.read",
  SYS_SETTINGS_GENERAL_UPDATE: "system.settings.general.update",
  SYS_SETTINGS_SMTP_READ: "system.settings.smtp.read",
  SYS_SETTINGS_SMTP_UPDATE: "system.settings.smtp.update",
  SYS_SETTINGS_SECURITY_READ: "system.settings.security.read",
  SYS_SETTINGS_SECURITY_UPDATE: "system.settings.security.update",
  SYS_SETTINGS_BRANDING_READ: "system.settings.branding.read",
  SYS_SETTINGS_BRANDING_UPDATE: "system.settings.branding.update",
  SYS_SETTINGS_EMAIL_TEMPLATES_READ: "system.settings.emailTemplates.read",
  SYS_SETTINGS_EMAIL_TEMPLATES_UPDATE: "system.settings.emailTemplates.update",

  // System: Files & Audit
  SYS_FILES_LIST: "system.files.list",
  SYS_FILES_READ: "system.files.read",
  SYS_FILES_DELETE: "system.files.delete",
  SYS_AUDIT_READ: "system.audit.read",

  // System: Workflows
  SYS_WORKFLOWS_RULES_LIST: "system.workflows.rules.list",
  SYS_WORKFLOWS_RULES_CREATE: "system.workflows.rules.create",
  SYS_WORKFLOWS_RULES_UPDATE: "system.workflows.rules.update",
  SYS_WORKFLOWS_RULES_DELETE: "system.workflows.rules.delete",
  SYS_WORKFLOWS_RUNS_LIST: "system.workflows.runs.list",
  SYS_WORKFLOWS_RUNS_READ: "system.workflows.runs.read",

  // System: Inbox
  SYS_INBOX_EMAILS_LIST: "system.inbox.emails.list",
  SYS_INBOX_EMAILS_READ: "system.inbox.emails.read",
  SYS_INBOX_EMAILS_CREATE: "system.inbox.emails.create",
  SYS_INBOX_EMAILS_UPDATE: "system.inbox.emails.update",
  SYS_INBOX_EMAILS_DELETE: "system.inbox.emails.delete",

  // System: Security (API Keys)
  SYS_SECURITY_API_KEYS_LIST: "system.security.apiKeys.list",
  SYS_SECURITY_API_KEYS_READ: "system.security.apiKeys.read",
  SYS_SECURITY_API_KEYS_CREATE: "system.security.apiKeys.create",
  SYS_SECURITY_API_KEYS_REVOKE: "system.security.apiKeys.revoke",

  // Admin (self)
  ADMIN_ME_READ: "admin.me.read",
  ADMIN_ME_UPDATE: "admin.me.update",
  ADMIN_PREFS_READ: "admin.preferences.read",
  ADMIN_PREFS_UPDATE: "admin.preferences.update",
  ADMIN_NOTIFICATIONS_READ: "admin.notifications.read",
});

// Flat, ordered list of all permission codes
export const ALL_PERMISSIONS = Object.freeze(
  Object.values(PERMISSIONS)
    .filter((v) => typeof v === "string" && v.trim().length)
    .map((v) => v.trim())
    .sort()
);

// Group permissions by module/area to power dynamic role management UIs
export const PERMISSION_GROUPS = Object.freeze({
  tickets: [
    PERMISSIONS.TICKETS_LIST,
    PERMISSIONS.TICKETS_READ,
    PERMISSIONS.TICKETS_CREATE,
    PERMISSIONS.TICKETS_UPDATE,
    PERMISSIONS.TICKETS_DELETE,
    PERMISSIONS.TICKETS_ASSIGN,
    PERMISSIONS.TICKETS_RELEASE,
    PERMISSIONS.TICKETS_CLAIM,
    PERMISSIONS.TICKETS_UNCLAIM,
    PERMISSIONS.TICKETS_STATUS_SET,
    PERMISSIONS.TICKETS_PRIORITY_SET,
    PERMISSIONS.TICKETS_SEVERITY_SET,
    PERMISSIONS.TICKETS_NOTES_READ,
    PERMISSIONS.TICKETS_NOTES_ADD,
    PERMISSIONS.TICKETS_WATCHERS_READ,
    PERMISSIONS.TICKETS_WATCHERS_ADD,
    PERMISSIONS.TICKETS_WATCHERS_REMOVE,
    PERMISSIONS.TICKETS_ATTACHMENTS_READ,
    PERMISSIONS.TICKETS_ATTACHMENTS_ADD,
    PERMISSIONS.TICKETS_EVENTS_READ,
    PERMISSIONS.TICKETS_CLOSE,
    PERMISSIONS.TICKETS_REOPEN,
  ],
  knowledge: [
    PERMISSIONS.KNOW_FAQS_LIST,
    PERMISSIONS.KNOW_FAQS_READ,
    PERMISSIONS.KNOW_FAQS_CREATE,
    PERMISSIONS.KNOW_FAQS_UPDATE,
    PERMISSIONS.KNOW_FAQS_DELETE,
    PERMISSIONS.KNOW_FAQ_ORIGINS_LIST,
    PERMISSIONS.KNOW_FAQ_ORIGINS_CREATE,
    PERMISSIONS.KNOW_FAQ_ORIGINS_DELETE,
    PERMISSIONS.KNOW_KB_ARTICLES_LIST,
    PERMISSIONS.KNOW_KB_ARTICLES_READ,
    PERMISSIONS.KNOW_KB_ARTICLES_CREATE,
    PERMISSIONS.KNOW_KB_ARTICLES_UPDATE,
    PERMISSIONS.KNOW_KB_ARTICLES_DELETE,
    PERMISSIONS.KNOW_KB_TAGS_LIST,
    PERMISSIONS.KNOW_KB_TAGS_CREATE,
    PERMISSIONS.KNOW_KB_TAGS_DELETE,
    PERMISSIONS.KNOW_KB_TAGMAP_LIST,
    PERMISSIONS.KNOW_KB_TAGMAP_CREATE,
    PERMISSIONS.KNOW_KB_TAGMAP_DELETE,
    PERMISSIONS.KNOW_KB_RATINGS_LIST,
    PERMISSIONS.KNOW_KB_RATINGS_DELETE,
    PERMISSIONS.KNOW_VIDEOS_LIST,
    PERMISSIONS.KNOW_VIDEOS_READ,
    PERMISSIONS.KNOW_VIDEOS_CREATE,
    PERMISSIONS.KNOW_VIDEOS_UPDATE,
    PERMISSIONS.KNOW_VIDEOS_DELETE,
    PERMISSIONS.KNOW_VIDEO_CATEGORIES_LIST,
    PERMISSIONS.KNOW_VIDEO_CATEGORIES_CREATE,
    PERMISSIONS.KNOW_VIDEO_CATEGORIES_UPDATE,
    PERMISSIONS.KNOW_VIDEO_CATEGORIES_DELETE,
    PERMISSIONS.KNOW_SEARCH_RUN,
  ],
  analytics: [
    PERMISSIONS.ANALYTICS_DASHBOARDS_VIEW,
    PERMISSIONS.ANALYTICS_REPORTS_RUN,
    PERMISSIONS.ANALYTICS_REPORTS_EXPORT,
    PERMISSIONS.ANALYTICS_EXPORTS_DOWNLOAD,
  ],
  system_users: [
    PERMISSIONS.SYS_USERS_LIST,
    PERMISSIONS.SYS_USERS_READ,
    PERMISSIONS.SYS_USERS_CREATE,
    PERMISSIONS.SYS_USERS_UPDATE,
    PERMISSIONS.SYS_USERS_DELETE,
    PERMISSIONS.SYS_USERS_ROLES_ASSIGN,
    PERMISSIONS.SYS_USERS_ROLES_REMOVE,
    PERMISSIONS.USERS_MANAGE,
  ],
  system_roles: [
    PERMISSIONS.SYS_ROLES_LIST,
    PERMISSIONS.SYS_ROLES_READ,
    PERMISSIONS.SYS_ROLES_CREATE,
    PERMISSIONS.SYS_ROLES_UPDATE,
    PERMISSIONS.SYS_ROLES_DELETE,
    PERMISSIONS.SYS_ROLES_PERMS_LIST,
    PERMISSIONS.SYS_ROLES_PERMS_ADD,
    PERMISSIONS.SYS_ROLES_PERMS_REMOVE,
    PERMISSIONS.ROLES_MANAGE,
  ],
  system_lookups: [
    PERMISSIONS.SYS_LOOKUPS_STATUSES_LIST,
    PERMISSIONS.SYS_LOOKUPS_STATUSES_CREATE,
    PERMISSIONS.SYS_LOOKUPS_STATUSES_UPDATE,
    PERMISSIONS.SYS_LOOKUPS_STATUSES_DELETE,
    PERMISSIONS.SYS_LOOKUPS_PRIORITIES_LIST,
    PERMISSIONS.SYS_LOOKUPS_PRIORITIES_CREATE,
    PERMISSIONS.SYS_LOOKUPS_PRIORITIES_UPDATE,
    PERMISSIONS.SYS_LOOKUPS_PRIORITIES_DELETE,
    PERMISSIONS.SYS_LOOKUPS_SEVERITIES_LIST,
    PERMISSIONS.SYS_LOOKUPS_SEVERITIES_CREATE,
    PERMISSIONS.SYS_LOOKUPS_SEVERITIES_UPDATE,
    PERMISSIONS.SYS_LOOKUPS_SEVERITIES_DELETE,
    PERMISSIONS.SYS_LOOKUPS_SOURCES_LIST,
    PERMISSIONS.SYS_LOOKUPS_SOURCES_CREATE,
    PERMISSIONS.SYS_LOOKUPS_SOURCES_UPDATE,
    PERMISSIONS.SYS_LOOKUPS_SOURCES_DELETE,
    PERMISSIONS.SYS_LOOKUPS_SYSTEM_CATEGORY_LIST,
    PERMISSIONS.SYS_LOOKUPS_SYSTEM_CATEGORY_CREATE,
    PERMISSIONS.SYS_LOOKUPS_SYSTEM_CATEGORY_UPDATE,
    PERMISSIONS.SYS_LOOKUPS_SYSTEM_CATEGORY_DELETE,
    PERMISSIONS.SYS_LOOKUPS_SYSTEMS_LIST,
    PERMISSIONS.SYS_LOOKUPS_SYSTEMS_READ,
    PERMISSIONS.SYS_LOOKUPS_SYSTEMS_CREATE,
    PERMISSIONS.SYS_LOOKUPS_SYSTEMS_UPDATE,
    PERMISSIONS.SYS_LOOKUPS_SYSTEMS_DELETE,
    PERMISSIONS.SYS_LOOKUPS_SYSTEM_MODULES_LIST,
    PERMISSIONS.SYS_LOOKUPS_SYSTEM_MODULES_READ,
    PERMISSIONS.SYS_LOOKUPS_SYSTEM_MODULES_CREATE,
    PERMISSIONS.SYS_LOOKUPS_SYSTEM_MODULES_UPDATE,
    PERMISSIONS.SYS_LOOKUPS_SYSTEM_MODULES_DELETE,
    PERMISSIONS.SYS_LOOKUPS_ISSUE_CATEGORIES_LIST,
    PERMISSIONS.SYS_LOOKUPS_ISSUE_CATEGORIES_READ,
    PERMISSIONS.SYS_LOOKUPS_ISSUE_CATEGORIES_CREATE,
    PERMISSIONS.SYS_LOOKUPS_ISSUE_CATEGORIES_UPDATE,
    PERMISSIONS.SYS_LOOKUPS_ISSUE_CATEGORIES_DELETE,
    PERMISSIONS.SETTINGS_MANAGE,
  ],
  system_agents: [
    PERMISSIONS.SYS_AGENTS_GROUPS_LIST,
    PERMISSIONS.SYS_AGENTS_GROUPS_READ,
    PERMISSIONS.SYS_AGENTS_GROUPS_CREATE,
    PERMISSIONS.SYS_AGENTS_GROUPS_UPDATE,
    PERMISSIONS.SYS_AGENTS_GROUPS_DELETE,
    PERMISSIONS.SYS_AGENTS_GROUP_MEMBERS_LIST,
    PERMISSIONS.SYS_AGENTS_GROUP_MEMBERS_ADD,
    PERMISSIONS.SYS_AGENTS_GROUP_MEMBERS_REMOVE,
    PERMISSIONS.SYS_AGENTS_TIERS_LIST,
    PERMISSIONS.SYS_AGENTS_TIERS_READ,
    PERMISSIONS.SYS_AGENTS_TIERS_CREATE,
    PERMISSIONS.SYS_AGENTS_TIERS_UPDATE,
    PERMISSIONS.SYS_AGENTS_TIERS_DELETE,
    PERMISSIONS.SYS_AGENTS_TIER_MEMBERS_LIST,
    PERMISSIONS.SYS_AGENTS_TIER_MEMBERS_ADD,
    PERMISSIONS.SYS_AGENTS_TIER_MEMBERS_REMOVE,
    PERMISSIONS.SYSTEM_MANAGE,
  ],
  system_settings: [
    PERMISSIONS.SYS_SETTINGS_GENERAL_READ,
    PERMISSIONS.SYS_SETTINGS_GENERAL_UPDATE,
    PERMISSIONS.SYS_SETTINGS_SMTP_READ,
    PERMISSIONS.SYS_SETTINGS_SMTP_UPDATE,
    PERMISSIONS.SYS_SETTINGS_SECURITY_READ,
    PERMISSIONS.SYS_SETTINGS_SECURITY_UPDATE,
    PERMISSIONS.SYS_SETTINGS_BRANDING_READ,
    PERMISSIONS.SYS_SETTINGS_BRANDING_UPDATE,
    PERMISSIONS.SYS_SETTINGS_EMAIL_TEMPLATES_READ,
    PERMISSIONS.SYS_SETTINGS_EMAIL_TEMPLATES_UPDATE,
    PERMISSIONS.SETTINGS_MANAGE,
  ],
  system_workflows: [
    PERMISSIONS.SYS_WORKFLOWS_RULES_LIST,
    PERMISSIONS.SYS_WORKFLOWS_RULES_CREATE,
    PERMISSIONS.SYS_WORKFLOWS_RULES_UPDATE,
    PERMISSIONS.SYS_WORKFLOWS_RULES_DELETE,
    PERMISSIONS.SYS_WORKFLOWS_RUNS_LIST,
    PERMISSIONS.SYS_WORKFLOWS_RUNS_READ,
    PERMISSIONS.WORKFLOWS_MANAGE,
  ],
  system_inbox: [
    PERMISSIONS.SYS_INBOX_EMAILS_LIST,
    PERMISSIONS.SYS_INBOX_EMAILS_READ,
    PERMISSIONS.SYS_INBOX_EMAILS_CREATE,
    PERMISSIONS.SYS_INBOX_EMAILS_UPDATE,
    PERMISSIONS.SYS_INBOX_EMAILS_DELETE,
    PERMISSIONS.INBOX_MANAGE,
  ],
  system_files_audit: [
    PERMISSIONS.SYS_FILES_LIST,
    PERMISSIONS.SYS_FILES_READ,
    PERMISSIONS.SYS_FILES_DELETE,
    PERMISSIONS.SYS_AUDIT_READ,
    PERMISSIONS.FILES_READ,
    PERMISSIONS.AUDIT_READ,
  ],
  system_security_api_keys: [
    PERMISSIONS.SYS_SECURITY_API_KEYS_LIST,
    PERMISSIONS.SYS_SECURITY_API_KEYS_READ,
    PERMISSIONS.SYS_SECURITY_API_KEYS_CREATE,
    PERMISSIONS.SYS_SECURITY_API_KEYS_REVOKE,
    PERMISSIONS.API_KEYS_MANAGE,
  ],
});

// Human-friendly labels for each permission code
export const PERMISSION_LABELS = Object.freeze({
  // Tickets
  "tickets.list": "Tickets: List",
  "tickets.read": "Tickets: Read",
  "tickets.create": "Tickets: Create",
  "tickets.update": "Tickets: Update",
  "tickets.delete": "Tickets: Delete",
  "tickets.assign": "Tickets: Assign",
  "tickets.release": "Tickets: Release",
  "tickets.claim": "Tickets: Claim",
  "tickets.unclaim": "Tickets: Unclaim",
  "tickets.status.set": "Tickets: Set Status",
  "tickets.priority.set": "Tickets: Set Priority",
  "tickets.severity.set": "Tickets: Set Severity",
  "tickets.notes.read": "Tickets: Notes Read",
  "tickets.notes.add": "Tickets: Notes Add",
  "tickets.watchers.read": "Tickets: Watchers Read",
  "tickets.watchers.add": "Tickets: Watchers Add",
  "tickets.watchers.remove": "Tickets: Watchers Remove",
  "tickets.attachments.read": "Tickets: Attachments Read",
  "tickets.attachments.add": "Tickets: Attachments Add",
  "tickets.events.read": "Tickets: Events Read",
  "tickets.close": "Tickets: Close",
  "tickets.reopen": "Tickets: Reopen",

  // Knowledge (subset shown)
  "knowledge.faqs.list": "Knowledge: FAQs List",
  "knowledge.faqs.read": "Knowledge: FAQs Read",
  "knowledge.faqs.create": "Knowledge: FAQs Create",
  "knowledge.faqs.update": "Knowledge: FAQs Update",
  "knowledge.faqs.delete": "Knowledge: FAQs Delete",
  "knowledge.faqs.origins.list": "Knowledge: FAQ Origins List",
  "knowledge.faqs.origins.create": "Knowledge: FAQ Origins Create",
  "knowledge.faqs.origins.delete": "Knowledge: FAQ Origins Delete",
  "knowledge.kb.articles.list": "Knowledge: KB Articles List",
  "knowledge.kb.articles.read": "Knowledge: KB Articles Read",
  "knowledge.kb.articles.create": "Knowledge: KB Articles Create",
  "knowledge.kb.articles.update": "Knowledge: KB Articles Update",
  "knowledge.kb.articles.delete": "Knowledge: KB Articles Delete",
  "knowledge.kb.tags.list": "Knowledge: KB Tags List",
  "knowledge.kb.tags.create": "Knowledge: KB Tags Create",
  "knowledge.kb.tags.delete": "Knowledge: KB Tags Delete",
  "knowledge.kb.tagMap.list": "Knowledge: KB Tag Map List",
  "knowledge.kb.tagMap.create": "Knowledge: KB Tag Map Create",
  "knowledge.kb.tagMap.delete": "Knowledge: KB Tag Map Delete",
  "knowledge.kb.ratings.list": "Knowledge: KB Ratings List",
  "knowledge.kb.ratings.delete": "Knowledge: KB Ratings Delete",
  "knowledge.videos.list": "Knowledge: Videos List",
  "knowledge.videos.read": "Knowledge: Videos Read",
  "knowledge.videos.create": "Knowledge: Videos Create",
  "knowledge.videos.update": "Knowledge: Videos Update",
  "knowledge.videos.delete": "Knowledge: Videos Delete",
  "knowledge.videoCategories.list": "Knowledge: Video Categories List",
  "knowledge.videoCategories.create": "Knowledge: Video Categories Create",
  "knowledge.videoCategories.update": "Knowledge: Video Categories Update",
  "knowledge.videoCategories.delete": "Knowledge: Video Categories Delete",
  "knowledge.search.run": "Knowledge: Search Run",

  // Analytics
  "analytics.dashboards.view": "Analytics: Dashboards View",
  "analytics.reports.run": "Analytics: Reports Run",
  "analytics.reports.export": "Analytics: Reports Export",
  "analytics.exports.download": "Analytics: Exports Download",

  // System Users
  "system.users.list": "System: Users List",
  "system.users.read": "System: Users Read",
  "system.users.create": "System: Users Create",
  "system.users.update": "System: Users Update",
  "system.users.delete": "System: Users Delete",
  "system.users.roles.assign": "System: Users Roles Assign",
  "system.users.roles.remove": "System: Users Roles Remove",

  // System Roles
  "system.roles.list": "System: Roles List",
  "system.roles.read": "System: Roles Read",
  "system.roles.create": "System: Roles Create",
  "system.roles.update": "System: Roles Update",
  "system.roles.delete": "System: Roles Delete",
  "system.roles.permissions.list": "System: Roles Permissions List",
  "system.roles.permissions.add": "System: Roles Permissions Add",
  "system.roles.permissions.remove": "System: Roles Permissions Remove",

  // Lookups
  "system.lookups.statuses.list": "Lookups: Statuses List",
  "system.lookups.statuses.create": "Lookups: Statuses Create",
  "system.lookups.statuses.update": "Lookups: Statuses Update",
  "system.lookups.statuses.delete": "Lookups: Statuses Delete",
  "system.lookups.priorities.list": "Lookups: Priorities List",
  "system.lookups.priorities.create": "Lookups: Priorities Create",
  "system.lookups.priorities.update": "Lookups: Priorities Update",
  "system.lookups.priorities.delete": "Lookups: Priorities Delete",
  "system.lookups.severities.list": "Lookups: Severities List",
  "system.lookups.severities.create": "Lookups: Severities Create",
  "system.lookups.severities.update": "Lookups: Severities Update",
  "system.lookups.severities.delete": "Lookups: Severities Delete",
  "system.lookups.sources.list": "Lookups: Sources List",
  "system.lookups.sources.create": "Lookups: Sources Create",
  "system.lookups.sources.update": "Lookups: Sources Update",
  "system.lookups.sources.delete": "Lookups: Sources Delete",
  "system.lookups.systemCategory.list": "Lookups: System Category List",
  "system.lookups.systemCategory.create": "Lookups: System Category Create",
  "system.lookups.systemCategory.update": "Lookups: System Category Update",
  "system.lookups.systemCategory.delete": "Lookups: System Category Delete",
  "system.lookups.systems.list": "Lookups: Systems List",
  "system.lookups.systems.read": "Lookups: Systems Read",
  "system.lookups.systems.create": "Lookups: Systems Create",
  "system.lookups.systems.update": "Lookups: Systems Update",
  "system.lookups.systems.delete": "Lookups: Systems Delete",
  "system.lookups.systemModules.list": "Lookups: System Modules List",
  "system.lookups.systemModules.read": "Lookups: System Modules Read",
  "system.lookups.systemModules.create": "Lookups: System Modules Create",
  "system.lookups.systemModules.update": "Lookups: System Modules Update",
  "system.lookups.systemModules.delete": "Lookups: System Modules Delete",
  "system.lookups.issueCategories.list": "Lookups: Issue Categories List",
  "system.lookups.issueCategories.read": "Lookups: Issue Categories Read",
  "system.lookups.issueCategories.create": "Lookups: Issue Categories Create",
  "system.lookups.issueCategories.update": "Lookups: Issue Categories Update",
  "system.lookups.issueCategories.delete": "Lookups: Issue Categories Delete",

  // Agents
  "system.agents.groups.list": "Agents: Groups List",
  "system.agents.groups.read": "Agents: Groups Read",
  "system.agents.groups.create": "Agents: Groups Create",
  "system.agents.groups.update": "Agents: Groups Update",
  "system.agents.groups.delete": "Agents: Groups Delete",
  "system.agents.groupMembers.list": "Agents: Group Members List",
  "system.agents.groupMembers.add": "Agents: Group Members Add",
  "system.agents.groupMembers.remove": "Agents: Group Members Remove",
  "system.agents.tiers.list": "Agents: Tiers List",
  "system.agents.tiers.read": "Agents: Tiers Read",
  "system.agents.tiers.create": "Agents: Tiers Create",
  "system.agents.tiers.update": "Agents: Tiers Update",
  "system.agents.tiers.delete": "Agents: Tiers Delete",
  "system.agents.tierMembers.list": "Agents: Tier Members List",
  "system.agents.tierMembers.add": "Agents: Tier Members Add",
  "system.agents.tierMembers.remove": "Agents: Tier Members Remove",

  // Settings
  "system.settings.general.read": "Settings: General Read",
  "system.settings.general.update": "Settings: General Update",
  "system.settings.smtp.read": "Settings: SMTP Read",
  "system.settings.smtp.update": "Settings: SMTP Update",
  "system.settings.security.read": "Settings: Security Read",
  "system.settings.security.update": "Settings: Security Update",
  "system.settings.branding.read": "Settings: Branding Read",
  "system.settings.branding.update": "Settings: Branding Update",
  "system.settings.emailTemplates.read": "Settings: Email Templates Read",
  "system.settings.emailTemplates.update": "Settings: Email Templates Update",

  // Files & Audit
  "system.files.list": "Files: List",
  "system.files.read": "Files: Read",
  "system.files.delete": "Files: Delete",
  "system.audit.read": "Audit: Read",

  // Workflows
  "system.workflows.rules.list": "Workflows: Rules List",
  "system.workflows.rules.create": "Workflows: Rules Create",
  "system.workflows.rules.update": "Workflows: Rules Update",
  "system.workflows.rules.delete": "Workflows: Rules Delete",
  "system.workflows.runs.list": "Workflows: Runs List",
  "system.workflows.runs.read": "Workflows: Runs Read",

  // Inbox
  "system.inbox.emails.list": "Inbox: Emails List",
  "system.inbox.emails.read": "Inbox: Emails Read",
  "system.inbox.emails.create": "Inbox: Emails Create",
  "system.inbox.emails.update": "Inbox: Emails Update",
  "system.inbox.emails.delete": "Inbox: Emails Delete",

  // API Keys
  "system.security.apiKeys.list": "API Keys: List",
  "system.security.apiKeys.read": "API Keys: Read",
  "system.security.apiKeys.create": "API Keys: Create",
  "system.security.apiKeys.revoke": "API Keys: Revoke",

  // Admin (self)
  "admin.me.read": "Admin: Me Read",
  "admin.me.update": "Admin: Me Update",
  "admin.preferences.read": "Admin: Preferences Read",
  "admin.preferences.update": "Admin: Preferences Update",
  "admin.notifications.read": "Admin: Notifications Read",
});

export function isPermission(name) {
  const v = typeof name === "string" ? name.trim() : "";
  return ALL_PERMISSIONS.includes(v);
}

// Default roles blueprint used by seeding scripts
export const DEFAULT_ROLES = Object.freeze({
  SUPERUSER: { code: 'superuser', name: 'Superuser', description: 'Full access to all features' },
  AGENT: {
    code: 'agent',
    name: 'Agent',
    description: 'Support agent with core ticket handling capabilities',
    permissions: [
      // Tickets: core lifecycle and collaboration
      PERMISSIONS.TICKETS_LIST,
      PERMISSIONS.TICKETS_READ,
      PERMISSIONS.TICKETS_CREATE,
      PERMISSIONS.TICKETS_UPDATE,
      PERMISSIONS.TICKETS_ASSIGN,
      PERMISSIONS.TICKETS_RELEASE,
      PERMISSIONS.TICKETS_CLAIM,
      PERMISSIONS.TICKETS_UNCLAIM,
      PERMISSIONS.TICKETS_STATUS_SET,
      PERMISSIONS.TICKETS_PRIORITY_SET,
      PERMISSIONS.TICKETS_SEVERITY_SET,
      PERMISSIONS.TICKETS_CLOSE,
      PERMISSIONS.TICKETS_REOPEN,
      PERMISSIONS.TICKETS_NOTES_READ,
      PERMISSIONS.TICKETS_NOTES_ADD,
      PERMISSIONS.TICKETS_WATCHERS_READ,
      PERMISSIONS.TICKETS_WATCHERS_ADD,
      PERMISSIONS.TICKETS_WATCHERS_REMOVE,
      PERMISSIONS.TICKETS_ATTACHMENTS_READ,
      PERMISSIONS.TICKETS_ATTACHMENTS_ADD,
      PERMISSIONS.TICKETS_EVENTS_READ,
    ],
  },
});
