import { Router } from "express";
import statuses from "./statuses.js";
import priorities from "./priorities.js";
import severities from "./severities.js";
import sources from "./sources.js";
import systems from "./systems.js";
import systemModules from "./system-modules.js";
import issueCategories from "./issue-categories.js";
import systemCategory from "./system-category.js";
const r = Router();
r.use("/statuses", statuses);
r.use("/priorities", priorities);
r.use("/severities", severities);
r.use("/sources", sources);
r.use("/systems", systems);
r.use("/system-modules", systemModules);
r.use("/issue-categories", issueCategories);
r.use("/system-category", systemCategory);
export default r;
